### ISSUE TITLE
[Event Delete] Different error message

### ISSUE THREAD

**Issue by benchan911** [AY1920S2-CS2113T-T12-4/tp#210]
Error message in the user guide seemed longer.

![image](https://user-images.githubusercontent.com/42601850/79042780-212a1500-7c2d-11ea-9c90-564e6ae3db7a.png)

![image](https://user-images.githubusercontent.com/42601850/79042781-271ff600-7c2d-11ea-9ba8-2111f9519c77.png)

**Comment by lowjiayee** [comment]
This is what I see with the latest build (today 7pm). Can you show how does your event list look like before the command `event delete i/4`? @benchan911 

![image](https://user-images.githubusercontent.com/42570474/79044174-43746080-7c36-11ea-9813-15c99a3f650c.png)

**Comment by lowjiayee** [comment]
Never mind, I've found how this is shown.
![image](https://user-images.githubusercontent.com/42570474/79044474-e11c5f80-7c37-11ea-8364-19076e136d98.png)
