### ISSUE TITLE
`performance add` bug when adding student

### ISSUE THREAD

**Issue by lowjiayee** [AY1920S2-CS2113T-T12-4/tp#225]
![image](https://user-images.githubusercontent.com/42570474/79043705-5afe1a00-7c33-11ea-8f23-43e7a679b287.png)

the app asks user to record next student, when actually the multiline command has ended.

Below is the studentlist used.
![image](https://user-images.githubusercontent.com/42570474/79043746-c21bce80-7c33-11ea-9093-422aac7a8656.png)

**Comment by Anqi-nus** [comment]
solved.
