### ISSUE TITLE
`performance edit` no message shown with invalid parameter

### ISSUE THREAD

**Issue by lowjiayee** [AY1920S2-CS2113T-T12-4/tp#227]
![image](https://user-images.githubusercontent.com/42570474/79043844-71f13c00-7c34-11ea-9d87-3f912b0049a6.png)

When user enters "name ***" but needs to enter "name" or "result", no prompts are shown to tell him/her that his/her input is wrong.

**Comment by Anqi-nus** [comment]
solved
