### ISSUE TITLE
Link studentList for easy integration into Attendance/Performance

### ISSUE THREAD

**Issue by lowjiayee** [AY1920S2-CS2113T-T12-4/tp#64]
Duke -> name -> add event or add studentList 
(studentList has attributes **listName** and **studentName**)

event add ..., prompts for a studentList (create one, or import from existing?)

Option 1: Create
1. Prompts for studentName
2. Prompts for attendance/performance
3. Repeat from step 1, unless user chooses to stop

Option 2: Import
1. User chooses a studentList among all existing studentLists
2. studentList prompts attendance/performance of each student, 1 by 1.

**Comment by lowjiayee** [comment]
@harithadiv Please read this to understand the changes to Attendance/Performance implementation

**Comment by benchan911** [comment]
@lowjiayee I think we separate the issue. So this issue focus on the adding of studentList to attendanceList, performanceList
